// <auto-generated />
using System;
using FrotaMan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrotaMan.Migrations
{
    [DbContext(typeof(FleetContext))]
    partial class FleetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FrotaMan.Models.MaintenanceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Odometer")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "odometer");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("maintenance");
                });

            modelBuilder.Entity("FrotaMan.Models.RefuellingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Odometer")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "odometer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("refuelling");
                });

            modelBuilder.Entity("FrotaMan.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuelType")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "fuelType");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasAnnotation("Relational:JsonPropertyName", "licensePlate");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "model");

                    b.Property<int>("Odometer")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "odometer");

                    b.Property<int>("TankVolume")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "tankVolume");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("vehicle");

                    b.HasDiscriminator<string>("type").HasValue("VehicleModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FrotaMan.Models.CarModel", b =>
                {
                    b.HasBaseType("FrotaMan.Models.VehicleModel");

                    b.ToTable("vehicle");

                    b.HasDiscriminator().HasValue("car");
                });

            modelBuilder.Entity("FrotaMan.Models.MotorcycleModel", b =>
                {
                    b.HasBaseType("FrotaMan.Models.VehicleModel");

                    b.ToTable("vehicle");

                    b.HasDiscriminator().HasValue("motorcycle");
                });

            modelBuilder.Entity("FrotaMan.Models.TruckModel", b =>
                {
                    b.HasBaseType("FrotaMan.Models.VehicleModel");

                    b.ToTable("vehicle");

                    b.HasDiscriminator().HasValue("truck");
                });

            modelBuilder.Entity("FrotaMan.Models.MaintenanceModel", b =>
                {
                    b.HasOne("FrotaMan.Models.VehicleModel", "Fleet")
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("FrotaMan.Models.RefuellingModel", b =>
                {
                    b.HasOne("FrotaMan.Models.VehicleModel", "Fleet")
                        .WithMany("Refuellings")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("FrotaMan.Models.VehicleModel", b =>
                {
                    b.Navigation("Maintenances");

                    b.Navigation("Refuellings");
                });
#pragma warning restore 612, 618
        }
    }
}
